### ISSUE TITLE
issue on git push sometimes

### ISSUE THREAD

**Issue by otakup0pe** [otakup0pe/avakas#3]
```
$ avakas bump . patch
Already on master branch
Version updated from 1.2.3 to 1.2.4
Traceback (most recent call last):
  File "/Users/freedmj/opt/pyz/bin/avakas", line 485, in <module>
    main()
  File "/Users/freedmj/opt/pyz/bin/avakas", line 461, in main
    write_git(repo, directory, version, opt)
  File "/Users/freedmj/opt/pyz/bin/avakas", line 165, in write_git
    git_push(repo, opt)
  File "/Users/freedmj/opt/pyz/bin/avakas", line 125, in git_push
    info = info[0]
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/git/util.py", line 701, in __getitem__
    return list.__getitem__(self, index)
IndexError: list index out of range
```

Everything still seems to get pushed. Might be an issue with with how we are parsing the git response.

**Comment by otakup0pe** [comment]
Memory is fuzzy but I'm wondering if this maybe has to do with cloned repositories that are lacking an `origin` remote ?

**Comment by otakup0pe** [comment]
![](https://38.media.tumblr.com/tumblr_lnxsouaNMK1qblpyfo1_250.gif)
